### ISSUE TITLE
Support for .NET standard 2.0 - which would give support for .NET framework >= 4.6.1

### ISSUE THREAD

**Issue by Alex-ley** [stulzq/RSAExtensions#3]
Because .NET standard 2.1 added so many new APIs, .NET framework won't be supporting it for the foreseeable future (https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

I wanted to use this NuGet package with a project that targets .NET framework 4.6.1 (or I could target 4.7.2 or 4.8 etc.) but it obviously is currently not compatible.

Do you need to target .NET standard >= 2.1 only? Or could you use multi-targeting to compile for .NET standard 2.0 as well, please? I don't know how non-trivial this would be for you, but I thought it's worth asking. Thanks.

As Microsoft says here (https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/):

> Library authors who need to support .NET Framework customers should stay on .NET Standard 2.0. In fact, most libraries should be able to stay on .NET Standard 2.0, as the API additions are largely for advanced scenarios. However, this doesn’t mean that library authors cannot take advantage of these APIs even if they have to support .NET Framework. In those cases they can use multi-targeting to compile for both .NET Standard 2.0 as well as .NET Standard 2.1. This allows writing code that can expose more features or provide a more efficient implementation on runtimes that support .NET Standard 2.1 while not giving up on the bigger reach that .NET Standard 2.0 offers.

**Comment by Alex-ley** [comment]
Perhaps I can answer my own question with a bit more investigation.

I assume it would be difficult / impossible as the methods you use such as the following, are only available in .NET framework 5.0 RC, .NET core 3.0, and .NET standard 2.1.

Is that basically why you can only really support .NET standard >= 2.1?

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.exportrsaprivatekey?view=netcore-3.1

**Comment by stulzq** [comment]
You can try https://github.com/stulzq/RSAUtil

**Comment by Alex-ley** [comment]
Thanks a lot! Not sure how I missed that repo... 😂 

I did manage to do XML <-> PEM last night in python but having the option to do it in .NET or python would be useful. I'll check out your other repo 👌 

Thanks
