### ISSUE TITLE
能否支持私钥加密，公钥解密

### ISSUE THREAD

**Issue by platstar** [stulzq/RSAExtensions#4]
1.原文有提到 **.NET 中的RSA仅支持 公钥加密，私钥解密**
請問RSAExtenions能否支持這個功能? 或者目前有無比較好的替代方案

2.若是同時ImportPrivateKey和ImportPublicKey則會有以下錯誤
雖然PrivateKey本身己包括PublicKey資料, 為什麼ImportPublicKey會發生這個異常呢
ImportPublicKey的內容跟私鑰一樣也是從相同System.Security.Cryptography.RSA.Create(1024) 導出來的
![image](https://user-images.githubusercontent.com/4907156/209745774-ca40b5ba-ae24-4646-b75c-e09746bad89f.png)

**Comment by stulzq** [comment]
你可以直接使用 `Portable.BouncyCastle` 尝试一下
